export type RooteStackParams = {
    Inicio:undefined,
    Login:undefined,
    Registro:undefined,
    Home:undefined,
    Ubication:undefined,
    Permissions:undefined,
    TypeUser:undefined,
    Tabs:undefined,
    CourseDetail:any,
    Courses: any,
    RoomChat:any,
    MyCourses: any,
    CourseNew: any,
    CourseUpdate: any,
    SubscriptionAdd: any,
    Perfil: any,
    ExamDo: any,
    ExamNew: any,
    ExamList: any,
    ExamView: any,
    ExamUpdate: any,
    QuestionNew: any,
    QuestionUpdate: any
}
